---
title: "Plot eQTL results"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, root.dir = here::here())

set.seed(1)
```

# Libraries

```{r}
library(tidyverse)
library(data.table)
library(here)
library(patchwork)
```

# Inputs

```{r}
# Both loseq and gtex filtered for maf >= 0.05. GTEx filtered for qval <= 0.05 pairs.

# list files for loseq results with gtex overlap - already filtered for q <= 0.05, maf >= 0.05 gtex pairs
#loseq_files <- list.files(path = here("analysis/qtl/loseq18/cis/"), pattern = "_loseq.filtered.txt.gz", full.names = TRUE)
loseq_files <- list.files(path = here("analysis/qtl/cis/"), pattern = "_loseq.filtered.txt.gz", full.names = TRUE)

# list files for gtex results - already filtered for q <= 0.05, maf >= 0.05 gtex pairs
#gtex_files <- list.files(path = here("analysis/qtl/loseq18/cis/"), pattern = "_gtex.filtered.txt.gz", full.names = TRUE)
gtex_files <- list.files(path = here("analysis/qtl/cis/"), pattern = "_gtex.filtered.txt.gz", full.names = TRUE)

# bootstrap files
#loseq_boot_files <- list.files(path = here("analysis/qtl/loseq18/cis/"), pattern = "_bootstrapping.pi1.txt.gz", full.names = TRUE)
loseq_boot_files <- list.files(path = here("analysis/qtl/cis/"), pattern = "_bootstrapping.pi1.txt.gz", full.names = TRUE)

# results files
# loseq_results_files <- list.files(path = here("analysis/qtl/loseq18/cis/"), pattern = "_replication.metrics.txt.gz", full.names = TRUE)
loseq_results_files <- list.files(path = here("analysis/qtl/cis/"), pattern = "_replication.metrics.txt.gz", full.names = TRUE)

# list gtex and loseq tissues
# loseq_tis <- unlist(lapply(loseq_files, function(x) {gsub(basename(x), pattern = ".cis_qtl_allpairs_allchr_annotated.txt.gz_loseq.filtered.txt.gz", replacement = "")}))
loseq_tis <- unlist(lapply(loseq_files, function(x) {gsub(basename(x), pattern = "_loseq.filtered.txt.gz", replacement = "")}))

rep_tissues <- here("data/gtex/representative_tissues.10.txt") # will add extra tissues

out_path <- here("analysis/qtl/")
# fig_path <- here("analysis/qtl/figs/eqtl_replication_loseq18_")
fig_path <- here("analysis/qtl/figs/eqtl_replication_")
```

# Functions

```{r}
source(here("src/base_functions.R"))
```

# Data

```{r}
# loseq gene pairs
loseq_dfs <- lapply(loseq_files, function(x) {fread(x, data.table = FALSE, nThread = 10)}) # this is slow but after this it's fine
names(loseq_dfs) <- loseq_tis

# loseq results
loseq_results <- lapply(loseq_results_files, function(x) {fread(x, data.table = FALSE, nThread = 10)})
names(loseq_results) <- loseq_tis

# loseq bootstrapping
loseq_boot <- lapply(loseq_boot_files, function(x) {fread(x, data.table = FALSE, nThread = 10)})
names(loseq_boot) <- loseq_tis

# gtex gene pairs
gtex_dfs <- lapply(gtex_files, function(x) {fread(x, data.table = FALSE, nThread = 10)})
names(gtex_dfs) <- loseq_tis

gtex_tis <- fread(here(rep_tissues), data.table = FALSE) # add kidney cortex, esophagus, spleen, lung, fibroblasts
gtex_tis <- c(gtex_tis$SMTSD, "Esophagus - Mucosa", "Kidney - Cortex", "Cells - Cultured fibroblasts", "Lung", "Spleen")

tis_labs <- c("Artery - Tibial", "Muscle - Skeletal", "Brain - Cortex", "Brain - Cerebellum", "EBVs", "Nerve - Tibial", "Thyroid", "Skin", "Whole Blood", "Testis", "Esophagus - Mucosa", "Kidney - Cortex", "Fibroblasts", "Lung", "Spleen")
names(tis_labs) <- gtex_tis
```

# Format colors

```{r}
source(here("src/gtex_loseq_colors.R"))

#myColors <- myColors[c(gtex_tis, loseq_tis)]
```

# Format

```{r}
pi1 <- lapply(loseq_results, function(x) {
  x %>% select(gtex_tissue, pi1) %>% mutate(pi1 = round(pi1, digits = 3))
})

loseq_boot_plot <- lapply(1:length(loseq_tis), function(x) {
  temp1 <- loseq_boot[[x]] %>% pivot_longer(cols = everything(), names_to = "gtex_tissue", values_to = "bootstrapped_pi1")
  temp2 <- gtex_dfs[[x]] %>% select(tissue, tissue_id) %>% dplyr::rename("gtex_tissue" = tissue_id) %>% distinct()
  out <- merge(temp1, temp2, by = "gtex_tissue")
  return(out)
})

pi1 <- lapply(1:length(loseq_tis), function(x) {
  temp <- gtex_dfs[[x]] %>% select(tissue, tissue_id) %>% dplyr::rename("gtex_tissue" = tissue_id) %>% distinct()
  out <- merge(pi1[[x]], temp, by = "gtex_tissue")
  return(out)
})

names(pi1) <- loseq_tis
names(loseq_boot_plot) <- loseq_tis
```


# Calculate p values

Compare pi1 to null pi1's. Sum number of null pi1s > actual pi1. Divide by 1000 --> p-value. If sum = 0, then set p-value to 1/1000.

```{r}
gtex_tis_all <- unique(colnames(loseq_boot$buccal))

pi1 <- lapply(1:length(loseq_tis), function(x) {
  
  temp_boot <- loseq_boot[[x]]
  temp_pi1 <- pi1[[x]]
  
  pvals <- lapply(gtex_tis_all, function(y) {
    true_pi1 <- temp_pi1[temp_pi1$gtex_tissue == y,]$pi1
    ct <- sum(temp_boot[, y] > true_pi1) + 1
    pval <- ifelse(ct/1000 == 1001/1000, 1, ct/1000)
  })
  
  pvals <- unlist(pvals)
  names(pvals) <- gtex_tis_all
  
  pvals_df <- data.frame("gtex_tissue" = names(pvals), "p_value" = pvals)
  out_pi1 <- merge(temp_pi1, pvals_df, by = "gtex_tissue")
  #out_pi1 <- out_pi1 %>% mutate("significant" = ifelse(p_value <= 0.05, "Significant", "Non-significant"))
  out_pi1 <- out_pi1 %>% mutate("perm_pval" = case_when(
    p_value == 0.001 ~ "== 0.001",
    p_value <= 0.05 & p_value > 0.001 ~ "0.001-0.05",
    p_value > 0.05 ~ "> 0.05"
  ))
  return(out_pi1)
  
})

names(pi1) <- loseq_tis
```

# Add pvalues to long bootstrapping df

```{r}
loseq_boot_plot <- lapply(1:length(loseq_tis), function(x) {
  out <- merge(loseq_boot_plot[[x]], pi1[[x]], by = c("gtex_tissue", "tissue"))
  return(out)
})
```


# Plot null vs observed pi1

```{r}
sig_colors <- c("== 0.001" = RColorBrewer::brewer.pal(12, "Paired")[6], "0.001-0.05" = RColorBrewer::brewer.pal(12, "Paired")[5], "> 0.05" = "black")
sig_size <- c("== 0.001" = 3, "0.001-0.05" = 2, "> 0.05" = 1)

pi1_plots <- lapply(1:length(loseq_tis), function(x) {
  
  ggplot(data = loseq_boot_plot[[x]], aes(x = reorder(tissue, pi1), y = bootstrapped_pi1, fill = tissue)) +
  geom_violin(draw_quantiles = TRUE) +
    geom_point(data = pi1[[x]], aes(x = tissue, y = pi1, color = perm_pval, size = perm_pval)) +
  #geom_point(data = pi1[[x]], aes(x = tissue, y = pi1, color = significant, size = -log(p_value))) +
  #geom_hline(data = pi1[pi1$tissue %in% gtex_tis,], aes(yintercept = pi1), color = "red") +
  #geom_point(data = pi1[pi1$tissue %in% gtex_tis,], aes(x = tissue, y = pi1, color = significant, size = -log(p_value))) +
  #geom_text(data = pi1[pi1$tissue %in% gtex_tis,], aes(x = tissue, label = p.value)) +
  theme_bw() +
  theme(strip.text = element_text(angle = 0)) +
  guides(fill = "none") +
    ylab("pi1") +
    xlab("") +
  scale_y_continuous(breaks = seq(0, 0.5, 0.05), limits = c(0, 0.5)) +
  coord_flip() +
  #facet_wrap(~tissue, scales = "free", drop = TRUE, strip.position = "left", ncol = 1) +
  scale_fill_manual(values = myColors) +
  scale_color_manual(values = sig_colors) +
    scale_size_manual(values = sig_size) +
  #scale_x_discrete(labels = tis_labs) +
  ggtitle(paste0("Calculated pi1 vs null pi1 distribution: ", loseq_tis[x])) +
  theme(plot.title = element_text(size = 14),
                  plot.subtitle = element_text(size = 13),
                  axis.title = element_text(size = 13),
                  axis.title.y = element_text(vjust = 2),
                  axis.title.x = element_text(vjust = -0.75),
                  axis.text.x = element_text(size = 12, angle = 60, hjust = 1, vjust = 1),
          axis.text.y = element_text(size = 12),
                  strip.text = element_text(size = 12),
                  legend.title = element_text(size = 13),
                  legend.text = element_text(size = 12))
  
})
```

```{r}
for (i in 1:length(loseq_tis)) {
  ggsave(plot = pi1_plots[[i]], file = paste0(fig_path, loseq_tis[i], "_pi1_all.pdf"), useDingbats = FALSE, height = 10, width = 9)
}
```


```{r}
pi1_plots_select <- lapply(1:length(loseq_tis), function(x) {
  
  ggplot(data = loseq_boot_plot[[x]][loseq_boot_plot[[x]]$tissue %in% gtex_tis,], aes(x = reorder(tissue, pi1), y = bootstrapped_pi1, fill = tissue)) +
  geom_violin(draw_quantiles = TRUE) +
  #geom_point(data = pi1[[x]], aes(x = tissue, y = pi1, color = significant, size = -log(p_value))) +
  #geom_hline(data = pi1[pi1$tissue %in% gtex_tis,], aes(yintercept = pi1), color = "red") +
  #geom_point(data = pi1[[x]][pi1[[x]]$tissue %in% gtex_tis,], aes(x = tissue, y = pi1, color = significant, size = -log(p_value))) +
    geom_point(data = pi1[[x]][pi1[[x]]$tissue %in% gtex_tis,], aes(x = tissue, y = pi1, color = perm_pval, size = perm_pval)) +
  #geom_text(data = pi1[pi1$tissue %in% gtex_tis,], aes(x = tissue, label = p.value)) +
  theme_bw() +
  theme(strip.text = element_text(angle = 0)) +
  guides(fill = "none") +
    ylab("pi1") +
    xlab("") +
  scale_y_continuous(breaks = seq(0, 0.5, 0.05), limits = c(0, 0.5)) +
  coord_flip() +
  #facet_wrap(~tissue, scales = "free", drop = TRUE, strip.position = "left", ncol = 1) +
  scale_fill_manual(values = myColors) +
  scale_color_manual(values = sig_colors) +
    scale_size_manual(values = sig_size) +
  scale_x_discrete(labels = tis_labs) +
  #ggtitle(paste0("Calculated pi1 vs null pi1 distribution: ", loseq_tis[x])) +
  theme(plot.title = element_text(size = 14),
                  plot.subtitle = element_text(size = 13),
                  axis.title = element_text(size = 13),
                  axis.title.y = element_text(vjust = 2),
                  axis.title.x = element_text(vjust = -0.75),
                  axis.text.x = element_text(size = 12, angle = 60, hjust = 1, vjust = 1),
          axis.text.y = element_text(size = 12),
                  strip.text = element_text(size = 12),
                  legend.title = element_text(size = 13),
                  legend.text = element_text(size = 12))
  
})
```

```{r}
for (i in 1:length(loseq_tis)) {
  ggsave(plot = pi1_plots_select[[i]], file = paste0(fig_path, loseq_tis[i], "_pi1_select.pdf"), useDingbats = FALSE, width = 6, height = 5)
}
```

# Plot histograms

```{r}
# format plotting data
hist_dat <- vector(mode = "list", length = length(loseq_dfs))

for (i in 1:length(hist_dat)){
  hist_dat[[i]] <- left_join(gtex_dfs[[i]], loseq_dfs[[i]][, c("id", "loseq_pval")], by = "id")
}
```

```{r}
hist_plots <- vector(mode = "list", length = length(hist_dat))

for (i in 1:length(hist_plots)){
  
  hist_plots[[i]] <- hist_dat[[i]] %>%
    #filter(tissue %in% gtex_tis) %>% 
    ggplot(aes(x = round(loseq_pval, digits = 2))) +
    geom_histogram(aes(fill = tissue), breaks = seq(0, 1, by = 1/30)) +
    #geom_text(data = pi1[[i]], aes(label = paste0("pi1 = ", pi1)), x = 0.5, y = 50) +
    #scale_y_continuous(limits = c(0,200), breaks = seq(0,200,20)) +
    theme_bw() +
    theme(legend.position = "none") +
    #facet_wrap(~tissue, ncol = 5, nrow = 3, labeller = labeller(tissue = tis_labs)) +
    facet_wrap(~tissue, labeller = label_wrap_gen()) +
    scale_fill_manual(values = myColors) +
    ggtitle(paste0("GTEx eVariant-eGene replication in ", loseq_tis[[i]])) +
    xlab("Loseq p-value") +
    theme(plot.title = element_text(size = 14),
                  plot.subtitle = element_text(size = 13),
                  axis.title = element_text(size = 13),
                  axis.title.y = element_text(vjust = 2),
                  axis.title.x = element_text(vjust = -0.75),
                  axis.text.x = element_text(size = 12, angle = 60, hjust = 1, vjust = 1),
          axis.text.y = element_text(size = 12),
                  strip.text = element_text(size = 12),
                  legend.title = element_text(size = 13),
                  legend.text = element_text(size = 12))
   
}
```

```{r}
for (i in 1:length(loseq_tis)) {
  ggsave(plot = hist_plots[[i]], file = paste0(fig_path, loseq_tis[i], "_hist_all.pdf"), useDingbats = FALSE, width = 15, height = 15)
}
```

```{r}
hist_plots_select <- vector(mode = "list", length = length(hist_dat))

for (i in 1:length(hist_plots_select)){
  
  hist_plots_select[[i]] <- hist_dat[[i]] %>%
    filter(tissue %in% gtex_tis) %>% 
    ggplot(aes(x = round(loseq_pval, digits = 2))) +
    geom_histogram(aes(fill = tissue), breaks = seq(0, 1, by = 1/30)) +
    #geom_text(data = pi1[[i]], aes(label = paste0("pi1 = ", pi1)), x = 0.5, y = 50) +
    scale_y_continuous(breaks = seq(0,500,50)) +
    theme_bw() +
    theme(legend.position = "none") +
    facet_wrap(~tissue, ncol = 5, nrow = 3, labeller = labeller(tissue = tis_labs)) +
    scale_fill_manual(values = myColors) +
    ggtitle(paste0("GTEx eVariant-eGene replication in ", loseq_tis[[i]])) +
    xlab("Loseq p-value") +
    theme(plot.title = element_text(size = 14),
                  plot.subtitle = element_text(size = 13),
                  axis.title = element_text(size = 13),
                  axis.title.y = element_text(vjust = 2),
                  axis.title.x = element_text(vjust = -0.75),
                  axis.text.x = element_text(size = 12, angle = 60, hjust = 1, vjust = 1),
          axis.text.y = element_text(size = 12),
                  strip.text = element_text(size = 12),
                  legend.title = element_text(size = 13),
                  legend.text = element_text(size = 12))
   
}
```

```{r}
for (i in 1:length(loseq_tis)) {
  ggsave(plot = hist_plots_select[[i]], file = paste0(fig_path, loseq_tis[i], "_hist_select.pdf"), useDingbats = FALSE, height = 6, width = 10)
}
```

# Plots together

```{r}
buc <- hist_plots_select[[1]] + pi1_plots_select[[1]] + plot_layout(widths = c(3.5,1))

ggsave(buc, filename = paste0(fig_path, "buccal_15tis_hist_and_pi1.pdf"), width = 17, height = 6, useDingbats = FALSE)
```


```{r}
hair <- hist_plots_select[[2]] + pi1_plots_select[[2]] + plot_layout(widths = c(3.5,1))

ggsave(hair, filename = paste0(fig_path, "hair_15tis_hist_and_pi1.pdf"), width = 17, height = 6, useDingbats = FALSE)
```

```{r}
urine <- hist_plots_select[[3]] + pi1_plots_select[[3]] + plot_layout(widths = c(3.5,1))

ggsave(urine, filename = paste0(fig_path, "urine_15tis_hist_and_pi1.pdf"), width = 17, height = 6, useDingbats = FALSE)
```







